"""Jointly solve aligned framework tasks with a shared, generated evidence memory.

Never reads canonical solutions: only model outputs and their allowed acceptance
feedback from this run. Budget is six submissions per framework (18 per family).
"""
import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
from .core import ROOT, FRAMEWORKS, dump, tasks, prepare_runtime, evaluate, feedback, generate

POLICY = '''You are a quantum-code agent solving aligned versions of the same task
across Qiskit, Cirq and PennyLane. All shared programs below were generated by the
same model during this experiment. They are NOT reference solutions. A program
marked accepted passed a functional test but may still have limitations.

Use a successful peer implementation as an executable semantic witness: reconstruct
its initial state, gate sequence, control phases, parameter conventions, logical
qubit mapping, measured subset and returned classical-bit order. Translate these
semantics to the requested framework, preserving the original task constraints.
Qiskit counts label bits high-to-low; Cirq and PennyLane sample columns follow
explicit measurement order. Preserve logical behavior and numeric outcome indexing.
Do not blindly copy SDK-specific wire conventions, output types or assumptions.
If no peer is accepted, use failed attempts to avoid repeating a rejected approach;
derive a new justified implementation from the mathematical specification.

Return ONLY a complete Python module with all imports and the requested function.
Use the requested framework natively; do not execute another framework as a backend.
Do not hardcode a distribution, fabricate samples, read files or references, or
replace the requested quantum algorithm with a classical answer calculation.
Versions: Qiskit 0.46.0, Aer 0.13.3, Cirq 1.6.1, PennyLane 0.43.1, Python 3.11.
'''

def solve_family(family, run, initial_run, attempts, compiled=False):
    records={}
    for task in family:
        key=task['framework']+'_'+task['task_id']
        source=ROOT/'runs'/initial_run/key/'attempt_1/record.json'
        initial=json.loads(source.read_text())
        records[task['framework']]=[initial]
        dump(run/key/'attempt_1/record.json',initial)
    for round_number in range(2,attempts+1):
        for task in family:
            framework=task['framework']
            history=records[framework]
            if history[-1]['evaluation']['passed']:
                continue
            key=framework+'_'+task['task_id']
            folder=run/key/f'attempt_{round_number}'
            if (folder/'record.json').exists():
                record=json.loads((folder/'record.json').read_text())
            else:
                own=[{'code':r['generation']['code'],'feedback':feedback(r['evaluation'])} for r in history]
                peers=[]
                for peer in family:
                    if peer['framework']==framework:
                        continue
                    r=records[peer['framework']][-1]
                    peers.append({'framework':peer['framework'], 'prompt':peer['complete_prompt'],
                                  'accepted':r['evaluation']['passed'],
                                  'code':r['generation']['code'],
                                  'observed_output':r['evaluation'].get('output'),
                                  'error':r['evaluation'].get('error') if not r['evaluation']['ran'] else None})
                witness=next((p for p in peers if p['framework']=='qiskit' and p['accepted']),None)
                # Try deterministic lowering once per distinct accepted source.
                import hashlib
                source_hash=hashlib.sha256(witness['code'].encode()).hexdigest() if witness else None
                already_tried=any(r.get('compiled_source_sha256')==source_hash for r in history) if source_hash else True
                gate_constrained=task['category']=='DECOMPOSITION' or 'decompos' in task['complete_prompt'].lower()
                use_compiler=compiled and witness is not None and not already_tried and not gate_constrained
                prompt=task['complete_prompt']+'\n\n'+POLICY+'\nOwn previous attempts:\n'+json.dumps(own)+'\nShared peer evidence:\n'+json.dumps(peers)
                if use_compiler:
                    from .compiler import compile_witness
                    generation={'code':compile_witness(witness['code'],task['entry_point'],framework),
                                'usage':{},'seconds':0,'kind':'deterministic_compilation',
                                'source_framework':'qiskit','source_sha256':source_hash}
                    dump(folder/'generation.json',generation)
                elif (folder/'generation.json').exists():
                    generation=json.loads((folder/'generation.json').read_text())
                else:
                    generation=generate(prompt,folder)
                result=evaluate(task,generation['code'])
                if result.get('infra_error'):
                    raise RuntimeError(result['error'])
                record={'attempt':round_number,'generation':generation,'evaluation':result,
                        'accepted_peers':[p['framework'] for p in peers if p['accepted']]}
                if use_compiler:
                    record['compiled_source_sha256']=source_hash
                dump(folder/'record.json',record)
            history.append(record)
    results=[]
    for task in family:
        key=task['framework']+'_'+task['task_id']
        history=records[task['framework']]
        result={'key':key,'task_id':task['task_id'],'framework':task['framework'],
                'category':task['category'],'passed':history[-1]['evaluation']['passed'],
                'attempts':len(history),'records':history}
        dump(run/key/'result.json',result)
        results.append(result)
    return results

def main():
    p=argparse.ArgumentParser()
    p.add_argument('--run',required=True)
    p.add_argument('--initial-run',required=True)
    p.add_argument('--ids',default='04,06,09,14,25,40')
    p.add_argument('--attempts',type=int,default=6)
    p.add_argument('--workers',type=int,default=3)
    p.add_argument('--compiled',action='store_true')
    a=p.parse_args()
    prepare_runtime()
    run=ROOT/'runs'/a.run
    dump(run/'config.json',vars(a))
    all_tasks=tasks()
    families=[[t for t in all_tasks if t['task_id']==tid] for tid in a.ids.split(',')]
    results=[]
    with ThreadPoolExecutor(max_workers=a.workers) as pool:
        futures={pool.submit(solve_family,f,run,a.initial_run,a.attempts,a.compiled):f[0]['task_id'] for f in families}
        for future in as_completed(futures):
            tid=futures[future]
            try:
                rows=future.result()
                results.extend(rows)
                print('family',tid,[(r['framework'],r['passed'],r['attempts']) for r in rows],flush=True)
            except Exception as exc:
                dump(run/f'family_{tid}_error.json',{'error':str(exc)})
                print('family',tid,'ERROR',str(exc),flush=True)
            dump(run/'summary.json',{'expected':len(families)*3,'completed':len(results),
                                    'passed':sum(r['passed'] for r in results),
                                    'tasks':[{k:v for k,v in r.items() if k!='records'} for r in results]})

if __name__=='__main__':
    main()
